/**********************************************************************************
Problem 2
***********    
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms.By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four 
million, find the sum of the even-valued terms.
************************************************************************************/

#include<stdio.h>
#include<conio.h>
void main()
{
    int first_previous=2;
    int second_previous=1;
    long int limit=4000000;
    long int sum=2;
    long int fibo=0;
    while(fibo<=limit)
    {   
        fibo=first_previous+second_previous;
        second_previous=first_previous;
        first_previous=fibo;
        if(fibo%2==0)
        {
         sum=sum+fibo;  
        }
    }
    printf("%ld",sum);
}


// Answer:  4613732
